/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorEnrollmentMethodsPush;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * AppAuthenticatorEnrollmentMethods
 */
@JsonPropertyOrder({
  AppAuthenticatorEnrollmentMethods.JSON_PROPERTY_PUSH
})
@JsonTypeName("AppAuthenticatorEnrollment_methods")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AppAuthenticatorEnrollmentMethods {
  public static final String JSON_PROPERTY_PUSH = "push";
  @javax.annotation.Nullable
  private AppAuthenticatorEnrollmentMethodsPush push;

  public AppAuthenticatorEnrollmentMethods() {
  }

  public AppAuthenticatorEnrollmentMethods push(@javax.annotation.Nullable AppAuthenticatorEnrollmentMethodsPush push) {
    
    this.push = push;
    return this;
  }

  /**
   * Get push
   * @return push
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUSH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppAuthenticatorEnrollmentMethodsPush getPush() {
    return push;
  }


  @JsonProperty(JSON_PROPERTY_PUSH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPush(@javax.annotation.Nullable AppAuthenticatorEnrollmentMethodsPush push) {
    this.push = push;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAuthenticatorEnrollmentMethods appAuthenticatorEnrollmentMethods = (AppAuthenticatorEnrollmentMethods) o;
    return Objects.equals(this.push, appAuthenticatorEnrollmentMethods.push);
  }

  @Override
  public int hashCode() {
    return Objects.hash(push);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAuthenticatorEnrollmentMethods {\n");
    sb.append("    push: ").append(toIndentedString(push)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

