/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorEnrollmentDevice;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorEnrollmentLinks;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorEnrollmentMethods;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorEnrollmentUser;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * App authenticator enrollment object
 */
@JsonPropertyOrder({
  AppAuthenticatorEnrollment.JSON_PROPERTY_AUTHENTICATOR_ID,
  AppAuthenticatorEnrollment.JSON_PROPERTY_CREATED_DATE,
  AppAuthenticatorEnrollment.JSON_PROPERTY_DEVICE,
  AppAuthenticatorEnrollment.JSON_PROPERTY_ID,
  AppAuthenticatorEnrollment.JSON_PROPERTY_LAST_UPDATED,
  AppAuthenticatorEnrollment.JSON_PROPERTY_LINKS,
  AppAuthenticatorEnrollment.JSON_PROPERTY_METHODS,
  AppAuthenticatorEnrollment.JSON_PROPERTY_USER
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AppAuthenticatorEnrollment {
  public static final String JSON_PROPERTY_AUTHENTICATOR_ID = "authenticatorId";
  @javax.annotation.Nullable
  private String authenticatorId;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @javax.annotation.Nullable
  private OffsetDateTime createdDate;

  public static final String JSON_PROPERTY_DEVICE = "device";
  @javax.annotation.Nullable
  private AppAuthenticatorEnrollmentDevice device;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_LAST_UPDATED = "lastUpdated";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_LINKS = "links";
  @javax.annotation.Nullable
  private AppAuthenticatorEnrollmentLinks links;

  public static final String JSON_PROPERTY_METHODS = "methods";
  @javax.annotation.Nullable
  private AppAuthenticatorEnrollmentMethods methods;

  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nullable
  private AppAuthenticatorEnrollmentUser user;

  public AppAuthenticatorEnrollment() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public AppAuthenticatorEnrollment(
    @JsonProperty(JSON_PROPERTY_AUTHENTICATOR_ID) String authenticatorId, 
    @JsonProperty(JSON_PROPERTY_CREATED_DATE) OffsetDateTime createdDate, 
    @JsonProperty(JSON_PROPERTY_ID) String id, 
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED) OffsetDateTime lastUpdated
  ) {
    this();
    this.authenticatorId = authenticatorId;
    this.createdDate = createdDate;
    this.id = id;
    this.lastUpdated = lastUpdated;
  }

  /**
   * Get authenticatorId
   * @return authenticatorId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHENTICATOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthenticatorId() {
    return authenticatorId;
  }



  /**
   * Get createdDate
   * @return createdDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }



  public AppAuthenticatorEnrollment device(@javax.annotation.Nullable AppAuthenticatorEnrollmentDevice device) {
    
    this.device = device;
    return this;
  }

  /**
   * Get device
   * @return device
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppAuthenticatorEnrollmentDevice getDevice() {
    return device;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevice(@javax.annotation.Nullable AppAuthenticatorEnrollmentDevice device) {
    this.device = device;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }



  /**
   * Get lastUpdated
   * @return lastUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }



  public AppAuthenticatorEnrollment links(@javax.annotation.Nullable AppAuthenticatorEnrollmentLinks links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppAuthenticatorEnrollmentLinks getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@javax.annotation.Nullable AppAuthenticatorEnrollmentLinks links) {
    this.links = links;
  }

  public AppAuthenticatorEnrollment methods(@javax.annotation.Nullable AppAuthenticatorEnrollmentMethods methods) {
    
    this.methods = methods;
    return this;
  }

  /**
   * Get methods
   * @return methods
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METHODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppAuthenticatorEnrollmentMethods getMethods() {
    return methods;
  }


  @JsonProperty(JSON_PROPERTY_METHODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethods(@javax.annotation.Nullable AppAuthenticatorEnrollmentMethods methods) {
    this.methods = methods;
  }

  public AppAuthenticatorEnrollment user(@javax.annotation.Nullable AppAuthenticatorEnrollmentUser user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppAuthenticatorEnrollmentUser getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@javax.annotation.Nullable AppAuthenticatorEnrollmentUser user) {
    this.user = user;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAuthenticatorEnrollment appAuthenticatorEnrollment = (AppAuthenticatorEnrollment) o;
    return Objects.equals(this.authenticatorId, appAuthenticatorEnrollment.authenticatorId) &&
        Objects.equals(this.createdDate, appAuthenticatorEnrollment.createdDate) &&
        Objects.equals(this.device, appAuthenticatorEnrollment.device) &&
        Objects.equals(this.id, appAuthenticatorEnrollment.id) &&
        Objects.equals(this.lastUpdated, appAuthenticatorEnrollment.lastUpdated) &&
        Objects.equals(this.links, appAuthenticatorEnrollment.links) &&
        Objects.equals(this.methods, appAuthenticatorEnrollment.methods) &&
        Objects.equals(this.user, appAuthenticatorEnrollment.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticatorId, createdDate, device, id, lastUpdated, links, methods, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAuthenticatorEnrollment {\n");
    sb.append("    authenticatorId: ").append(toIndentedString(authenticatorId)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    methods: ").append(toIndentedString(methods)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

