/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorEnrollmentRequestDevice;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorEnrollmentRequestMethods;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * App authenticator enrollment request
 */
@JsonPropertyOrder({
  AppAuthenticatorEnrollmentRequest.JSON_PROPERTY_AUTHENTICATOR_ID,
  AppAuthenticatorEnrollmentRequest.JSON_PROPERTY_DEVICE,
  AppAuthenticatorEnrollmentRequest.JSON_PROPERTY_METHODS
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AppAuthenticatorEnrollmentRequest {
  public static final String JSON_PROPERTY_AUTHENTICATOR_ID = "authenticatorId";
  @javax.annotation.Nonnull
  private String authenticatorId;

  public static final String JSON_PROPERTY_DEVICE = "device";
  @javax.annotation.Nonnull
  private AppAuthenticatorEnrollmentRequestDevice device;

  public static final String JSON_PROPERTY_METHODS = "methods";
  @javax.annotation.Nonnull
  private AppAuthenticatorEnrollmentRequestMethods methods;

  public AppAuthenticatorEnrollmentRequest() {
  }

  public AppAuthenticatorEnrollmentRequest authenticatorId(@javax.annotation.Nonnull String authenticatorId) {
    
    this.authenticatorId = authenticatorId;
    return this;
  }

  /**
   * Get authenticatorId
   * @return authenticatorId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AUTHENTICATOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAuthenticatorId() {
    return authenticatorId;
  }


  @JsonProperty(JSON_PROPERTY_AUTHENTICATOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthenticatorId(@javax.annotation.Nonnull String authenticatorId) {
    this.authenticatorId = authenticatorId;
  }

  public AppAuthenticatorEnrollmentRequest device(@javax.annotation.Nonnull AppAuthenticatorEnrollmentRequestDevice device) {
    
    this.device = device;
    return this;
  }

  /**
   * Get device
   * @return device
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AppAuthenticatorEnrollmentRequestDevice getDevice() {
    return device;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDevice(@javax.annotation.Nonnull AppAuthenticatorEnrollmentRequestDevice device) {
    this.device = device;
  }

  public AppAuthenticatorEnrollmentRequest methods(@javax.annotation.Nonnull AppAuthenticatorEnrollmentRequestMethods methods) {
    
    this.methods = methods;
    return this;
  }

  /**
   * Get methods
   * @return methods
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METHODS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AppAuthenticatorEnrollmentRequestMethods getMethods() {
    return methods;
  }


  @JsonProperty(JSON_PROPERTY_METHODS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMethods(@javax.annotation.Nonnull AppAuthenticatorEnrollmentRequestMethods methods) {
    this.methods = methods;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAuthenticatorEnrollmentRequest appAuthenticatorEnrollmentRequest = (AppAuthenticatorEnrollmentRequest) o;
    return Objects.equals(this.authenticatorId, appAuthenticatorEnrollmentRequest.authenticatorId) &&
        Objects.equals(this.device, appAuthenticatorEnrollmentRequest.device) &&
        Objects.equals(this.methods, appAuthenticatorEnrollmentRequest.methods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticatorId, device, methods);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAuthenticatorEnrollmentRequest {\n");
    sb.append("    authenticatorId: ").append(toIndentedString(authenticatorId)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    methods: ").append(toIndentedString(methods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

