/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.KeyObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * AppAuthenticatorEnrollmentRequestDevice
 */
@JsonPropertyOrder({
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_SECURE_HARDWARE_PRESENT,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_CLIENT_INSTANCE_KEY,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_OS_VERSION,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_CLIENT_INSTANCE_BUNDLE_ID,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_PLATFORM,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_MANUFACTURER,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_DEVICE_ATTESTATION,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_CLIENT_INSTANCE_VERSION,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_CLIENT_INSTANCE_DEVICE_SDK_VERSION,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_MODEL,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_DISPLAY_NAME,
  AppAuthenticatorEnrollmentRequestDevice.JSON_PROPERTY_UDID
})
@JsonTypeName("AppAuthenticatorEnrollmentRequest_device")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AppAuthenticatorEnrollmentRequestDevice {
  public static final String JSON_PROPERTY_SECURE_HARDWARE_PRESENT = "secureHardwarePresent";
  @javax.annotation.Nullable
  private Boolean secureHardwarePresent;

  public static final String JSON_PROPERTY_CLIENT_INSTANCE_KEY = "clientInstanceKey";
  @javax.annotation.Nonnull
  private KeyObject.Raw clientInstanceKey;

  public static final String JSON_PROPERTY_OS_VERSION = "osVersion";
  @javax.annotation.Nonnull
  private String osVersion;

  public static final String JSON_PROPERTY_CLIENT_INSTANCE_BUNDLE_ID = "clientInstanceBundleId";
  @javax.annotation.Nonnull
  private String clientInstanceBundleId;

  /**
   * Gets or Sets platform
   */
  public enum PlatformEnum {
    ANDROID(String.valueOf("ANDROID")),
    
    IOS(String.valueOf("IOS"));

    private String value;

    PlatformEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PlatformEnum fromValue(String value) {
      for (PlatformEnum b : PlatformEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nonnull
  private PlatformEnum platform;

  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  @javax.annotation.Nullable
  private String manufacturer;

  public static final String JSON_PROPERTY_DEVICE_ATTESTATION = "deviceAttestation";
  @javax.annotation.Nullable
  private Object deviceAttestation;

  public static final String JSON_PROPERTY_CLIENT_INSTANCE_VERSION = "clientInstanceVersion";
  @javax.annotation.Nonnull
  private String clientInstanceVersion;

  public static final String JSON_PROPERTY_CLIENT_INSTANCE_DEVICE_SDK_VERSION = "clientInstanceDeviceSdkVersion";
  @javax.annotation.Nonnull
  private String clientInstanceDeviceSdkVersion;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nullable
  private String model;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nonnull
  private String displayName;

  public static final String JSON_PROPERTY_UDID = "udid";
  @javax.annotation.Nullable
  private String udid;

  public AppAuthenticatorEnrollmentRequestDevice() {
  }

  public AppAuthenticatorEnrollmentRequestDevice secureHardwarePresent(@javax.annotation.Nullable Boolean secureHardwarePresent) {
    
    this.secureHardwarePresent = secureHardwarePresent;
    return this;
  }

  /**
   * Indicates if the device is equipped with TPM storage for storing signing keys
   * @return secureHardwarePresent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECURE_HARDWARE_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSecureHardwarePresent() {
    return secureHardwarePresent;
  }


  @JsonProperty(JSON_PROPERTY_SECURE_HARDWARE_PRESENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecureHardwarePresent(@javax.annotation.Nullable Boolean secureHardwarePresent) {
    this.secureHardwarePresent = secureHardwarePresent;
  }

  public AppAuthenticatorEnrollmentRequestDevice clientInstanceKey(@javax.annotation.Nonnull KeyObject.Raw clientInstanceKey) {
    
    this.clientInstanceKey = clientInstanceKey;
    return this;
  }

  /**
   * Get clientInstanceKey
   * @return clientInstanceKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public KeyObject.Raw getClientInstanceKey() {
    return clientInstanceKey;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientInstanceKey(@javax.annotation.Nonnull KeyObject.Raw clientInstanceKey) {
    this.clientInstanceKey = clientInstanceKey;
  }

  public AppAuthenticatorEnrollmentRequestDevice osVersion(@javax.annotation.Nonnull String osVersion) {
    
    this.osVersion = osVersion;
    return this;
  }

  /**
   * Get osVersion
   * @return osVersion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OS_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOsVersion() {
    return osVersion;
  }


  @JsonProperty(JSON_PROPERTY_OS_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOsVersion(@javax.annotation.Nonnull String osVersion) {
    this.osVersion = osVersion;
  }

  public AppAuthenticatorEnrollmentRequestDevice clientInstanceBundleId(@javax.annotation.Nonnull String clientInstanceBundleId) {
    
    this.clientInstanceBundleId = clientInstanceBundleId;
    return this;
  }

  /**
   * Get clientInstanceBundleId
   * @return clientInstanceBundleId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_BUNDLE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientInstanceBundleId() {
    return clientInstanceBundleId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_BUNDLE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientInstanceBundleId(@javax.annotation.Nonnull String clientInstanceBundleId) {
    this.clientInstanceBundleId = clientInstanceBundleId;
  }

  public AppAuthenticatorEnrollmentRequestDevice platform(@javax.annotation.Nonnull PlatformEnum platform) {
    
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PlatformEnum getPlatform() {
    return platform;
  }


  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlatform(@javax.annotation.Nonnull PlatformEnum platform) {
    this.platform = platform;
  }

  public AppAuthenticatorEnrollmentRequestDevice manufacturer(@javax.annotation.Nullable String manufacturer) {
    
    this.manufacturer = manufacturer;
    return this;
  }

  /**
   * Get manufacturer
   * @return manufacturer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManufacturer() {
    return manufacturer;
  }


  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManufacturer(@javax.annotation.Nullable String manufacturer) {
    this.manufacturer = manufacturer;
  }

  public AppAuthenticatorEnrollmentRequestDevice deviceAttestation(@javax.annotation.Nullable Object deviceAttestation) {
    
    this.deviceAttestation = deviceAttestation;
    return this;
  }

  /**
   * Get deviceAttestation
   * @return deviceAttestation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_ATTESTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getDeviceAttestation() {
    return deviceAttestation;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_ATTESTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceAttestation(@javax.annotation.Nullable Object deviceAttestation) {
    this.deviceAttestation = deviceAttestation;
  }

  public AppAuthenticatorEnrollmentRequestDevice clientInstanceVersion(@javax.annotation.Nonnull String clientInstanceVersion) {
    
    this.clientInstanceVersion = clientInstanceVersion;
    return this;
  }

  /**
   * Get clientInstanceVersion
   * @return clientInstanceVersion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientInstanceVersion() {
    return clientInstanceVersion;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientInstanceVersion(@javax.annotation.Nonnull String clientInstanceVersion) {
    this.clientInstanceVersion = clientInstanceVersion;
  }

  public AppAuthenticatorEnrollmentRequestDevice clientInstanceDeviceSdkVersion(@javax.annotation.Nonnull String clientInstanceDeviceSdkVersion) {
    
    this.clientInstanceDeviceSdkVersion = clientInstanceDeviceSdkVersion;
    return this;
  }

  /**
   * Get clientInstanceDeviceSdkVersion
   * @return clientInstanceDeviceSdkVersion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_DEVICE_SDK_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientInstanceDeviceSdkVersion() {
    return clientInstanceDeviceSdkVersion;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_INSTANCE_DEVICE_SDK_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientInstanceDeviceSdkVersion(@javax.annotation.Nonnull String clientInstanceDeviceSdkVersion) {
    this.clientInstanceDeviceSdkVersion = clientInstanceDeviceSdkVersion;
  }

  public AppAuthenticatorEnrollmentRequestDevice model(@javax.annotation.Nullable String model) {
    
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }

  public AppAuthenticatorEnrollmentRequestDevice displayName(@javax.annotation.Nonnull String displayName) {
    
    this.displayName = displayName;
    return this;
  }

  /**
   * The device&#39;s display name
   * @return displayName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(@javax.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }

  public AppAuthenticatorEnrollmentRequestDevice udid(@javax.annotation.Nullable String udid) {
    
    this.udid = udid;
    return this;
  }

  /**
   * Get udid
   * @return udid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UDID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUdid() {
    return udid;
  }


  @JsonProperty(JSON_PROPERTY_UDID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUdid(@javax.annotation.Nullable String udid) {
    this.udid = udid;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAuthenticatorEnrollmentRequestDevice appAuthenticatorEnrollmentRequestDevice = (AppAuthenticatorEnrollmentRequestDevice) o;
    return Objects.equals(this.secureHardwarePresent, appAuthenticatorEnrollmentRequestDevice.secureHardwarePresent) &&
        Objects.equals(this.clientInstanceKey, appAuthenticatorEnrollmentRequestDevice.clientInstanceKey) &&
        Objects.equals(this.osVersion, appAuthenticatorEnrollmentRequestDevice.osVersion) &&
        Objects.equals(this.clientInstanceBundleId, appAuthenticatorEnrollmentRequestDevice.clientInstanceBundleId) &&
        Objects.equals(this.platform, appAuthenticatorEnrollmentRequestDevice.platform) &&
        Objects.equals(this.manufacturer, appAuthenticatorEnrollmentRequestDevice.manufacturer) &&
        Objects.equals(this.deviceAttestation, appAuthenticatorEnrollmentRequestDevice.deviceAttestation) &&
        Objects.equals(this.clientInstanceVersion, appAuthenticatorEnrollmentRequestDevice.clientInstanceVersion) &&
        Objects.equals(this.clientInstanceDeviceSdkVersion, appAuthenticatorEnrollmentRequestDevice.clientInstanceDeviceSdkVersion) &&
        Objects.equals(this.model, appAuthenticatorEnrollmentRequestDevice.model) &&
        Objects.equals(this.displayName, appAuthenticatorEnrollmentRequestDevice.displayName) &&
        Objects.equals(this.udid, appAuthenticatorEnrollmentRequestDevice.udid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secureHardwarePresent, clientInstanceKey, osVersion, clientInstanceBundleId, platform, manufacturer, deviceAttestation, clientInstanceVersion, clientInstanceDeviceSdkVersion, model, displayName, udid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAuthenticatorEnrollmentRequestDevice {\n");
    sb.append("    secureHardwarePresent: ").append(toIndentedString(secureHardwarePresent)).append("\n");
    sb.append("    clientInstanceKey: ").append(toIndentedString(clientInstanceKey)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    clientInstanceBundleId: ").append(toIndentedString(clientInstanceBundleId)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    deviceAttestation: ").append(toIndentedString(deviceAttestation)).append("\n");
    sb.append("    clientInstanceVersion: ").append(toIndentedString(clientInstanceVersion)).append("\n");
    sb.append("    clientInstanceDeviceSdkVersion: ").append(toIndentedString(clientInstanceDeviceSdkVersion)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    udid: ").append(toIndentedString(udid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

