/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * AppAuthenticatorMethodCapabilities
 */
@JsonPropertyOrder({
  AppAuthenticatorMethodCapabilities.JSON_PROPERTY_TRANSACTION_TYPES
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AppAuthenticatorMethodCapabilities {
  /**
   * Gets or Sets transactionTypes
   */
  public enum TransactionTypesEnum {
    LOGIN(String.valueOf("LOGIN")),
    
    CIBA(String.valueOf("CIBA"));

    private String value;

    TransactionTypesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TransactionTypesEnum fromValue(String value) {
      for (TransactionTypesEnum b : TransactionTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TRANSACTION_TYPES = "transactionTypes";
  @javax.annotation.Nullable
  private List<TransactionTypesEnum> transactionTypes = new ArrayList<>();

  public AppAuthenticatorMethodCapabilities() {
  }

  public AppAuthenticatorMethodCapabilities transactionTypes(@javax.annotation.Nullable List<TransactionTypesEnum> transactionTypes) {
    
    this.transactionTypes = transactionTypes;
    return this;
  }

  public AppAuthenticatorMethodCapabilities addTransactionTypesItem(TransactionTypesEnum transactionTypesItem) {
    if (this.transactionTypes == null) {
      this.transactionTypes = new ArrayList<>();
    }
    this.transactionTypes.add(transactionTypesItem);
    return this;
  }

  /**
   * Get transactionTypes
   * @return transactionTypes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TransactionTypesEnum> getTransactionTypes() {
    return transactionTypes;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionTypes(@javax.annotation.Nullable List<TransactionTypesEnum> transactionTypes) {
    this.transactionTypes = transactionTypes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAuthenticatorMethodCapabilities appAuthenticatorMethodCapabilities = (AppAuthenticatorMethodCapabilities) o;
    return Objects.equals(this.transactionTypes, appAuthenticatorMethodCapabilities.transactionTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAuthenticatorMethodCapabilities {\n");
    sb.append("    transactionTypes: ").append(toIndentedString(transactionTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

