/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorMethodCapabilities;
import com.okta.myaccount.myaccountmanagement.model.KeyObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * AppAuthenticatorEnrollmentRequestMethodsPushKeys
 */
@JsonPropertyOrder({
  AppAuthenticatorEnrollmentRequestMethodsPushKeys.JSON_PROPERTY_PROOF_OF_POSSESSION,
  AppAuthenticatorEnrollmentRequestMethodsPushKeys.JSON_PROPERTY_USER_VERIFICATION,
  AppAuthenticatorEnrollmentRequestMethodsPushKeys.JSON_PROPERTY_CAPABILITIES
})
@JsonTypeName("AppAuthenticatorEnrollmentRequest_methods_push_keys")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AppAuthenticatorEnrollmentRequestMethodsPushKeys {
  public static final String JSON_PROPERTY_PROOF_OF_POSSESSION = "proofOfPossession";
  @javax.annotation.Nonnull
  private KeyObject.Raw proofOfPossession;

  public static final String JSON_PROPERTY_USER_VERIFICATION = "userVerification";
  @javax.annotation.Nullable
  private KeyObject.Raw userVerification;

  public static final String JSON_PROPERTY_CAPABILITIES = "capabilities";
  @javax.annotation.Nullable
  private AppAuthenticatorMethodCapabilities capabilities;

  public AppAuthenticatorEnrollmentRequestMethodsPushKeys() {
  }

  public AppAuthenticatorEnrollmentRequestMethodsPushKeys proofOfPossession(@javax.annotation.Nonnull KeyObject.Raw proofOfPossession) {
    
    this.proofOfPossession = proofOfPossession;
    return this;
  }

  /**
   * Get proofOfPossession
   * @return proofOfPossession
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROOF_OF_POSSESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public KeyObject.Raw getProofOfPossession() {
    return proofOfPossession;
  }


  @JsonProperty(JSON_PROPERTY_PROOF_OF_POSSESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProofOfPossession(@javax.annotation.Nonnull KeyObject.Raw proofOfPossession) {
    this.proofOfPossession = proofOfPossession;
  }

  public AppAuthenticatorEnrollmentRequestMethodsPushKeys userVerification(@javax.annotation.Nullable KeyObject.Raw userVerification) {
    
    this.userVerification = userVerification;
    return this;
  }

  /**
   * Get userVerification
   * @return userVerification
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_VERIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public KeyObject.Raw getUserVerification() {
    return userVerification;
  }


  @JsonProperty(JSON_PROPERTY_USER_VERIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserVerification(@javax.annotation.Nullable KeyObject.Raw userVerification) {
    this.userVerification = userVerification;
  }

  public AppAuthenticatorEnrollmentRequestMethodsPushKeys capabilities(@javax.annotation.Nullable AppAuthenticatorMethodCapabilities capabilities) {
    
    this.capabilities = capabilities;
    return this;
  }

  /**
   * Get capabilities
   * @return capabilities
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPABILITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppAuthenticatorMethodCapabilities getCapabilities() {
    return capabilities;
  }


  @JsonProperty(JSON_PROPERTY_CAPABILITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapabilities(@javax.annotation.Nullable AppAuthenticatorMethodCapabilities capabilities) {
    this.capabilities = capabilities;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAuthenticatorEnrollmentRequestMethodsPushKeys appAuthenticatorEnrollmentRequestMethodsPushKeys = (AppAuthenticatorEnrollmentRequestMethodsPushKeys) o;
    return Objects.equals(this.proofOfPossession, appAuthenticatorEnrollmentRequestMethodsPushKeys.proofOfPossession) &&
        Objects.equals(this.userVerification, appAuthenticatorEnrollmentRequestMethodsPushKeys.userVerification) &&
        Objects.equals(this.capabilities, appAuthenticatorEnrollmentRequestMethodsPushKeys.capabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proofOfPossession, userVerification, capabilities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAuthenticatorEnrollmentRequestMethodsPushKeys {\n");
    sb.append("    proofOfPossession: ").append(toIndentedString(proofOfPossession)).append("\n");
    sb.append("    userVerification: ").append(toIndentedString(userVerification)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

