/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.HrefObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * AuthenticatorLinks
 */
@JsonPropertyOrder({
  AuthenticatorLinks.JSON_PROPERTY_SELF,
  AuthenticatorLinks.JSON_PROPERTY_ENROLL,
  AuthenticatorLinks.JSON_PROPERTY_ENROLLMENTS
})
@JsonTypeName("Authenticator__links")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AuthenticatorLinks {
  public static final String JSON_PROPERTY_SELF = "self";
  @javax.annotation.Nullable
  private HrefObject self;

  public static final String JSON_PROPERTY_ENROLL = "enroll";
  @javax.annotation.Nullable
  private HrefObject enroll;

  public static final String JSON_PROPERTY_ENROLLMENTS = "enrollments";
  @javax.annotation.Nullable
  private HrefObject enrollments;

  public AuthenticatorLinks() {
  }

  public AuthenticatorLinks self(@javax.annotation.Nullable HrefObject self) {
    
    this.self = self;
    return this;
  }

  /**
   * Get self
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObject getSelf() {
    return self;
  }


  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelf(@javax.annotation.Nullable HrefObject self) {
    this.self = self;
  }

  public AuthenticatorLinks enroll(@javax.annotation.Nullable HrefObject enroll) {
    
    this.enroll = enroll;
    return this;
  }

  /**
   * Get enroll
   * @return enroll
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENROLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObject getEnroll() {
    return enroll;
  }


  @JsonProperty(JSON_PROPERTY_ENROLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnroll(@javax.annotation.Nullable HrefObject enroll) {
    this.enroll = enroll;
  }

  public AuthenticatorLinks enrollments(@javax.annotation.Nullable HrefObject enrollments) {
    
    this.enrollments = enrollments;
    return this;
  }

  /**
   * Get enrollments
   * @return enrollments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENROLLMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObject getEnrollments() {
    return enrollments;
  }


  @JsonProperty(JSON_PROPERTY_ENROLLMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnrollments(@javax.annotation.Nullable HrefObject enrollments) {
    this.enrollments = enrollments;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticatorLinks authenticatorLinks = (AuthenticatorLinks) o;
    return Objects.equals(this.self, authenticatorLinks.self) &&
        Objects.equals(this.enroll, authenticatorLinks.enroll) &&
        Objects.equals(this.enrollments, authenticatorLinks.enrollments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, enroll, enrollments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticatorLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    enroll: ").append(toIndentedString(enroll)).append("\n");
    sb.append("    enrollments: ").append(toIndentedString(enrollments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

