/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets AuthenticatorKey
 */
public enum AuthenticatorKey {
  
  CUSTOM_APP("custom_app"),
  
  CUSTOM_OTP("custom_otp"),
  
  DUO("duo"),
  
  EXTERNAL_IDP("external_idp"),
  
  GOOGLE_OTP("google_otp"),
  
  OKTA_EMAIL("okta_email"),
  
  OKTA_PASSWORD("okta_password"),
  
  OKTA_VERIFY("okta_verify"),
  
  ONPREM_MFA("onprem_mfa"),
  
  PHONE_NUMBER("phone_number"),
  
  RSA_TOKEN("rsa_token"),
  
  SECURITY_QUESTION("security_question"),
  
  SYMANTEC_VIP("symantec_vip"),
  
  WEBAUTHN("webauthn"),
  
  YUBIKEY_TOKEN("yubikey_token");

  private String value;

  AuthenticatorKey(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AuthenticatorKey fromValue(String value) {
    for (AuthenticatorKey b : AuthenticatorKey.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

