/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.AuthenticatorEnrollment;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * AuthenticatorEmbedded
 */
@JsonPropertyOrder({
  AuthenticatorEmbedded.JSON_PROPERTY_ENROLLMENTS
})
@JsonTypeName("Authenticator__embedded")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AuthenticatorEmbedded {
  public static final String JSON_PROPERTY_ENROLLMENTS = "enrollments";
  @javax.annotation.Nullable
  private List<AuthenticatorEnrollment> enrollments = new ArrayList<>();

  public AuthenticatorEmbedded() {
  }

  public AuthenticatorEmbedded enrollments(@javax.annotation.Nullable List<AuthenticatorEnrollment> enrollments) {
    
    this.enrollments = enrollments;
    return this;
  }

  public AuthenticatorEmbedded addEnrollmentsItem(AuthenticatorEnrollment enrollmentsItem) {
    if (this.enrollments == null) {
      this.enrollments = new ArrayList<>();
    }
    this.enrollments.add(enrollmentsItem);
    return this;
  }

  /**
   * Get enrollments
   * @return enrollments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENROLLMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AuthenticatorEnrollment> getEnrollments() {
    return enrollments;
  }


  @JsonProperty(JSON_PROPERTY_ENROLLMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnrollments(@javax.annotation.Nullable List<AuthenticatorEnrollment> enrollments) {
    this.enrollments = enrollments;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticatorEmbedded authenticatorEmbedded = (AuthenticatorEmbedded) o;
    return Objects.equals(this.enrollments, authenticatorEmbedded.enrollments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enrollments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticatorEmbedded {\n");
    sb.append("    enrollments: ").append(toIndentedString(enrollments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

