/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.AuthenticatorEnrollmentLinks;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * Authenticator enrollment of the current user
 */
@JsonPropertyOrder({
  AuthenticatorEnrollment.JSON_PROPERTY_CAN_RESET,
  AuthenticatorEnrollment.JSON_PROPERTY_CAN_UNENROLL,
  AuthenticatorEnrollment.JSON_PROPERTY_CREATED,
  AuthenticatorEnrollment.JSON_PROPERTY_ID,
  AuthenticatorEnrollment.JSON_PROPERTY_LAST_CHALLENGED,
  AuthenticatorEnrollment.JSON_PROPERTY_NAME,
  AuthenticatorEnrollment.JSON_PROPERTY_NICKNAME,
  AuthenticatorEnrollment.JSON_PROPERTY_PROFILE,
  AuthenticatorEnrollment.JSON_PROPERTY_LINKS
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AuthenticatorEnrollment {
  public static final String JSON_PROPERTY_CAN_RESET = "canReset";
  @javax.annotation.Nullable
  private Boolean canReset;

  public static final String JSON_PROPERTY_CAN_UNENROLL = "canUnenroll";
  @javax.annotation.Nullable
  private Boolean canUnenroll;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_LAST_CHALLENGED = "lastChallenged";
  @javax.annotation.Nullable
  private String lastChallenged;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_NICKNAME = "nickname";
  @javax.annotation.Nullable
  private String nickname;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  @javax.annotation.Nullable
  private Object profile;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @javax.annotation.Nullable
  private AuthenticatorEnrollmentLinks links;

  public AuthenticatorEnrollment() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public AuthenticatorEnrollment(
    @JsonProperty(JSON_PROPERTY_CAN_RESET) Boolean canReset, 
    @JsonProperty(JSON_PROPERTY_CAN_UNENROLL) Boolean canUnenroll, 
    @JsonProperty(JSON_PROPERTY_CREATED) String created, 
    @JsonProperty(JSON_PROPERTY_ID) String id, 
    @JsonProperty(JSON_PROPERTY_LAST_CHALLENGED) String lastChallenged, 
    @JsonProperty(JSON_PROPERTY_PROFILE) Object profile
  ) {
    this();
    this.canReset = canReset;
    this.canUnenroll = canUnenroll;
    this.created = created;
    this.id = id;
    this.lastChallenged = lastChallenged;
    this.profile = profile;
  }

  /**
   * Get canReset
   * @return canReset
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_RESET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanReset() {
    return canReset;
  }



  /**
   * Get canUnenroll
   * @return canUnenroll
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_UNENROLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanUnenroll() {
    return canUnenroll;
  }



  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }



  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }



  /**
   * Get lastChallenged
   * @return lastChallenged
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_CHALLENGED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastChallenged() {
    return lastChallenged;
  }



  public AuthenticatorEnrollment name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public AuthenticatorEnrollment nickname(@javax.annotation.Nullable String nickname) {
    
    this.nickname = nickname;
    return this;
  }

  /**
   * Get nickname
   * @return nickname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NICKNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNickname() {
    return nickname;
  }


  @JsonProperty(JSON_PROPERTY_NICKNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNickname(@javax.annotation.Nullable String nickname) {
    this.nickname = nickname;
  }

  /**
   * Get profile
   * @return profile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getProfile() {
    return profile;
  }



  public AuthenticatorEnrollment links(@javax.annotation.Nullable AuthenticatorEnrollmentLinks links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuthenticatorEnrollmentLinks getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@javax.annotation.Nullable AuthenticatorEnrollmentLinks links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticatorEnrollment authenticatorEnrollment = (AuthenticatorEnrollment) o;
    return Objects.equals(this.canReset, authenticatorEnrollment.canReset) &&
        Objects.equals(this.canUnenroll, authenticatorEnrollment.canUnenroll) &&
        Objects.equals(this.created, authenticatorEnrollment.created) &&
        Objects.equals(this.id, authenticatorEnrollment.id) &&
        Objects.equals(this.lastChallenged, authenticatorEnrollment.lastChallenged) &&
        Objects.equals(this.name, authenticatorEnrollment.name) &&
        Objects.equals(this.nickname, authenticatorEnrollment.nickname) &&
        Objects.equals(this.profile, authenticatorEnrollment.profile) &&
        Objects.equals(this.links, authenticatorEnrollment.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canReset, canUnenroll, created, id, lastChallenged, name, nickname, profile, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticatorEnrollment {\n");
    sb.append("    canReset: ").append(toIndentedString(canReset)).append("\n");
    sb.append("    canUnenroll: ").append(toIndentedString(canUnenroll)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastChallenged: ").append(toIndentedString(lastChallenged)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

