/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.HrefObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * AuthenticatorEnrollmentLinks
 */
@JsonPropertyOrder({
  AuthenticatorEnrollmentLinks.JSON_PROPERTY_SELF,
  AuthenticatorEnrollmentLinks.JSON_PROPERTY_AUTHENTICATOR,
  AuthenticatorEnrollmentLinks.JSON_PROPERTY_MODIFY,
  AuthenticatorEnrollmentLinks.JSON_PROPERTY_UNENROLL
})
@JsonTypeName("AuthenticatorEnrollment__links")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class AuthenticatorEnrollmentLinks {
  public static final String JSON_PROPERTY_SELF = "self";
  @javax.annotation.Nullable
  private HrefObject self;

  public static final String JSON_PROPERTY_AUTHENTICATOR = "authenticator";
  @javax.annotation.Nullable
  private HrefObject authenticator;

  public static final String JSON_PROPERTY_MODIFY = "modify";
  @javax.annotation.Nullable
  private HrefObject modify;

  public static final String JSON_PROPERTY_UNENROLL = "unenroll";
  @javax.annotation.Nullable
  private HrefObject unenroll;

  public AuthenticatorEnrollmentLinks() {
  }

  public AuthenticatorEnrollmentLinks self(@javax.annotation.Nullable HrefObject self) {
    
    this.self = self;
    return this;
  }

  /**
   * Get self
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObject getSelf() {
    return self;
  }


  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelf(@javax.annotation.Nullable HrefObject self) {
    this.self = self;
  }

  public AuthenticatorEnrollmentLinks authenticator(@javax.annotation.Nullable HrefObject authenticator) {
    
    this.authenticator = authenticator;
    return this;
  }

  /**
   * Get authenticator
   * @return authenticator
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHENTICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObject getAuthenticator() {
    return authenticator;
  }


  @JsonProperty(JSON_PROPERTY_AUTHENTICATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthenticator(@javax.annotation.Nullable HrefObject authenticator) {
    this.authenticator = authenticator;
  }

  public AuthenticatorEnrollmentLinks modify(@javax.annotation.Nullable HrefObject modify) {
    
    this.modify = modify;
    return this;
  }

  /**
   * Get modify
   * @return modify
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObject getModify() {
    return modify;
  }


  @JsonProperty(JSON_PROPERTY_MODIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModify(@javax.annotation.Nullable HrefObject modify) {
    this.modify = modify;
  }

  public AuthenticatorEnrollmentLinks unenroll(@javax.annotation.Nullable HrefObject unenroll) {
    
    this.unenroll = unenroll;
    return this;
  }

  /**
   * Get unenroll
   * @return unenroll
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNENROLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObject getUnenroll() {
    return unenroll;
  }


  @JsonProperty(JSON_PROPERTY_UNENROLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnenroll(@javax.annotation.Nullable HrefObject unenroll) {
    this.unenroll = unenroll;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticatorEnrollmentLinks authenticatorEnrollmentLinks = (AuthenticatorEnrollmentLinks) o;
    return Objects.equals(this.self, authenticatorEnrollmentLinks.self) &&
        Objects.equals(this.authenticator, authenticatorEnrollmentLinks.authenticator) &&
        Objects.equals(this.modify, authenticatorEnrollmentLinks.modify) &&
        Objects.equals(this.unenroll, authenticatorEnrollmentLinks.unenroll);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, authenticator, modify, unenroll);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticatorEnrollmentLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    authenticator: ").append(toIndentedString(authenticator)).append("\n");
    sb.append("    modify: ").append(toIndentedString(modify)).append("\n");
    sb.append("    unenroll: ").append(toIndentedString(unenroll)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

