/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.CreateEmailRequestProfile;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * CreateEmailRequest
 */
@JsonPropertyOrder({
  CreateEmailRequest.JSON_PROPERTY_PROFILE,
  CreateEmailRequest.JSON_PROPERTY_SEND_EMAIL,
  CreateEmailRequest.JSON_PROPERTY_STATE,
  CreateEmailRequest.JSON_PROPERTY_ROLE
})
@JsonTypeName("createEmail_request")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class CreateEmailRequest {
  public static final String JSON_PROPERTY_PROFILE = "profile";
  @javax.annotation.Nonnull
  private CreateEmailRequestProfile profile;

  public static final String JSON_PROPERTY_SEND_EMAIL = "sendEmail";
  @javax.annotation.Nullable
  private Boolean sendEmail = true;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  /**
   * Gets or Sets role
   */
  public enum RoleEnum {
    PRIMARY(String.valueOf("PRIMARY")),
    
    SECONDARY(String.valueOf("SECONDARY"));

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private RoleEnum role;

  public CreateEmailRequest() {
  }

  public CreateEmailRequest profile(@javax.annotation.Nonnull CreateEmailRequestProfile profile) {
    
    this.profile = profile;
    return this;
  }

  /**
   * Get profile
   * @return profile
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CreateEmailRequestProfile getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProfile(@javax.annotation.Nonnull CreateEmailRequestProfile profile) {
    this.profile = profile;
  }

  public CreateEmailRequest sendEmail(@javax.annotation.Nullable Boolean sendEmail) {
    
    this.sendEmail = sendEmail;
    return this;
  }

  /**
   * Specifies whether Okta or the application sends an email to the end user
   * @return sendEmail
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEND_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSendEmail() {
    return sendEmail;
  }


  @JsonProperty(JSON_PROPERTY_SEND_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendEmail(@javax.annotation.Nullable Boolean sendEmail) {
    this.sendEmail = sendEmail;
  }

  public CreateEmailRequest state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Any application state that the client wishes to persist across the email challenge flow, and receive at the callback URL. Define the callback URL in the OIDC app configuration. This parameter proves to the client that the email link is verified. 
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }

  public CreateEmailRequest role(@javax.annotation.Nullable RoleEnum role) {
    
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RoleEnum getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(@javax.annotation.Nullable RoleEnum role) {
    this.role = role;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateEmailRequest createEmailRequest = (CreateEmailRequest) o;
    return Objects.equals(this.profile, createEmailRequest.profile) &&
        Objects.equals(this.sendEmail, createEmailRequest.sendEmail) &&
        Objects.equals(this.state, createEmailRequest.state) &&
        Objects.equals(this.role, createEmailRequest.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profile, sendEmail, state, role);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateEmailRequest {\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    sendEmail: ").append(toIndentedString(sendEmail)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

