/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.EmailLinksChallenge;
import com.okta.myaccount.myaccountmanagement.model.EmailLinksPoll;
import com.okta.myaccount.myaccountmanagement.model.EmailLinksSelf;
import com.okta.myaccount.myaccountmanagement.model.EmailLinksVerify;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * Discoverable resources related to the caller&#39;s email
 */
@JsonPropertyOrder({
  EmailLinks.JSON_PROPERTY_SELF,
  EmailLinks.JSON_PROPERTY_CHALLENGE,
  EmailLinks.JSON_PROPERTY_VERIFY,
  EmailLinks.JSON_PROPERTY_POLL
})
@JsonTypeName("Email__links")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class EmailLinks {
  public static final String JSON_PROPERTY_SELF = "self";
  @javax.annotation.Nullable
  private EmailLinksSelf self;

  public static final String JSON_PROPERTY_CHALLENGE = "challenge";
  @javax.annotation.Nullable
  private EmailLinksChallenge challenge;

  public static final String JSON_PROPERTY_VERIFY = "verify";
  @javax.annotation.Nullable
  private EmailLinksVerify verify;

  public static final String JSON_PROPERTY_POLL = "poll";
  @javax.annotation.Nullable
  private EmailLinksPoll poll;

  public EmailLinks() {
  }

  public EmailLinks self(@javax.annotation.Nullable EmailLinksSelf self) {
    
    this.self = self;
    return this;
  }

  /**
   * Get self
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmailLinksSelf getSelf() {
    return self;
  }


  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelf(@javax.annotation.Nullable EmailLinksSelf self) {
    this.self = self;
  }

  public EmailLinks challenge(@javax.annotation.Nullable EmailLinksChallenge challenge) {
    
    this.challenge = challenge;
    return this;
  }

  /**
   * Get challenge
   * @return challenge
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmailLinksChallenge getChallenge() {
    return challenge;
  }


  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChallenge(@javax.annotation.Nullable EmailLinksChallenge challenge) {
    this.challenge = challenge;
  }

  public EmailLinks verify(@javax.annotation.Nullable EmailLinksVerify verify) {
    
    this.verify = verify;
    return this;
  }

  /**
   * Get verify
   * @return verify
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmailLinksVerify getVerify() {
    return verify;
  }


  @JsonProperty(JSON_PROPERTY_VERIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerify(@javax.annotation.Nullable EmailLinksVerify verify) {
    this.verify = verify;
  }

  public EmailLinks poll(@javax.annotation.Nullable EmailLinksPoll poll) {
    
    this.poll = poll;
    return this;
  }

  /**
   * Get poll
   * @return poll
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmailLinksPoll getPoll() {
    return poll;
  }


  @JsonProperty(JSON_PROPERTY_POLL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPoll(@javax.annotation.Nullable EmailLinksPoll poll) {
    this.poll = poll;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailLinks emailLinks = (EmailLinks) o;
    return Objects.equals(this.self, emailLinks.self) &&
        Objects.equals(this.challenge, emailLinks.challenge) &&
        Objects.equals(this.verify, emailLinks.verify) &&
        Objects.equals(this.poll, emailLinks.poll);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, challenge, verify, poll);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("    verify: ").append(toIndentedString(verify)).append("\n");
    sb.append("    poll: ").append(toIndentedString(poll)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

