/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.HrefObjectHints;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * HrefObject
 */
@JsonPropertyOrder({
  HrefObject.JSON_PROPERTY_HINTS,
  HrefObject.JSON_PROPERTY_HREF,
  HrefObject.JSON_PROPERTY_NAME,
  HrefObject.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class HrefObject {
  public static final String JSON_PROPERTY_HINTS = "hints";
  @javax.annotation.Nullable
  private HrefObjectHints hints;

  public static final String JSON_PROPERTY_HREF = "href";
  @javax.annotation.Nonnull
  private String href;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  public HrefObject() {
  }

  public HrefObject hints(@javax.annotation.Nullable HrefObjectHints hints) {
    
    this.hints = hints;
    return this;
  }

  /**
   * Get hints
   * @return hints
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HrefObjectHints getHints() {
    return hints;
  }


  @JsonProperty(JSON_PROPERTY_HINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHints(@javax.annotation.Nullable HrefObjectHints hints) {
    this.hints = hints;
  }

  public HrefObject href(@javax.annotation.Nonnull String href) {
    
    this.href = href;
    return this;
  }

  /**
   * Link URI
   * @return href
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHref(@javax.annotation.Nonnull String href) {
    this.href = href;
  }

  public HrefObject name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Link name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public HrefObject type(@javax.annotation.Nullable String type) {
    
    this.type = type;
    return this;
  }

  /**
   * The media type of the link. If omitted, it is implicitly &#x60;application/json&#x60;.
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HrefObject hrefObject = (HrefObject) o;
    return Objects.equals(this.hints, hrefObject.hints) &&
        Objects.equals(this.href, hrefObject.href) &&
        Objects.equals(this.name, hrefObject.name) &&
        Objects.equals(this.type, hrefObject.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hints, href, name, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HrefObject {\n");
    sb.append("    hints: ").append(toIndentedString(hints)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

