/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.InlineObjectLinksVerify;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * Discoverable resources related to the phone challenge
 */
@JsonPropertyOrder({
  InlineObjectLinks.JSON_PROPERTY_VERIFY
})
@JsonTypeName("inline_object__links")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class InlineObjectLinks {
  public static final String JSON_PROPERTY_VERIFY = "verify";
  @javax.annotation.Nullable
  private InlineObjectLinksVerify verify;

  public InlineObjectLinks() {
  }

  public InlineObjectLinks verify(@javax.annotation.Nullable InlineObjectLinksVerify verify) {
    
    this.verify = verify;
    return this;
  }

  /**
   * Get verify
   * @return verify
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InlineObjectLinksVerify getVerify() {
    return verify;
  }


  @JsonProperty(JSON_PROPERTY_VERIFY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerify(@javax.annotation.Nullable InlineObjectLinksVerify verify) {
    this.verify = verify;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObjectLinks inlineObjectLinks = (InlineObjectLinks) o;
    return Objects.equals(this.verify, inlineObjectLinks.verify);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verify);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObjectLinks {\n");
    sb.append("    verify: ").append(toIndentedString(verify)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

