/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.OrganizationLinks;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * Org object
 */
@JsonPropertyOrder({
  Organization.JSON_PROPERTY_HELP_LINK,
  Organization.JSON_PROPERTY_NAME,
  Organization.JSON_PROPERTY_SUPPORT_EMAIL,
  Organization.JSON_PROPERTY_URL,
  Organization.JSON_PROPERTY_LINKS
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class Organization {
  public static final String JSON_PROPERTY_HELP_LINK = "helpLink";
  @javax.annotation.Nullable
  private String helpLink;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SUPPORT_EMAIL = "supportEmail";
  @javax.annotation.Nullable
  private String supportEmail;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_LINKS = "_links";
  @javax.annotation.Nullable
  private OrganizationLinks links;

  public Organization() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Organization(
    @JsonProperty(JSON_PROPERTY_HELP_LINK) String helpLink, 
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_SUPPORT_EMAIL) String supportEmail, 
    @JsonProperty(JSON_PROPERTY_URL) String url
  ) {
    this();
    this.helpLink = helpLink;
    this.name = name;
    this.supportEmail = supportEmail;
    this.url = url;
  }

  /**
   * The URL of the org&#39;s help resources
   * @return helpLink
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HELP_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHelpLink() {
    return helpLink;
  }



  /**
   * The name of the org
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }



  /**
   * The email address of the org support contact
   * @return supportEmail
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPORT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSupportEmail() {
    return supportEmail;
  }



  /**
   * The URL of the org
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }



  public Organization links(@javax.annotation.Nullable OrganizationLinks links) {
    
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrganizationLinks getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@javax.annotation.Nullable OrganizationLinks links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organization organization = (Organization) o;
    return Objects.equals(this.helpLink, organization.helpLink) &&
        Objects.equals(this.name, organization.name) &&
        Objects.equals(this.supportEmail, organization.supportEmail) &&
        Objects.equals(this.url, organization.url) &&
        Objects.equals(this.links, organization.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(helpLink, name, supportEmail, url, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    sb.append("    helpLink: ").append(toIndentedString(helpLink)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supportEmail: ").append(toIndentedString(supportEmail)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

