/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.PasswordResponseLinksSelfHints;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * Link to the resource (self)
 */
@JsonPropertyOrder({
  PasswordResponseLinksSelf.JSON_PROPERTY_HREF,
  PasswordResponseLinksSelf.JSON_PROPERTY_HINTS
})
@JsonTypeName("PasswordResponse__links_self")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class PasswordResponseLinksSelf {
  public static final String JSON_PROPERTY_HREF = "href";
  @javax.annotation.Nullable
  private String href;

  public static final String JSON_PROPERTY_HINTS = "hints";
  @javax.annotation.Nullable
  private PasswordResponseLinksSelfHints hints;

  public PasswordResponseLinksSelf() {
  }

  public PasswordResponseLinksSelf href(@javax.annotation.Nullable String href) {
    
    this.href = href;
    return this;
  }

  /**
   * Link URI
   * @return href
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHref(@javax.annotation.Nullable String href) {
    this.href = href;
  }

  public PasswordResponseLinksSelf hints(@javax.annotation.Nullable PasswordResponseLinksSelfHints hints) {
    
    this.hints = hints;
    return this;
  }

  /**
   * Get hints
   * @return hints
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PasswordResponseLinksSelfHints getHints() {
    return hints;
  }


  @JsonProperty(JSON_PROPERTY_HINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHints(@javax.annotation.Nullable PasswordResponseLinksSelfHints hints) {
    this.hints = hints;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordResponseLinksSelf passwordResponseLinksSelf = (PasswordResponseLinksSelf) o;
    return Objects.equals(this.href, passwordResponseLinksSelf.href) &&
        Objects.equals(this.hints, passwordResponseLinksSelf.hints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, hints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordResponseLinksSelf {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    hints: ").append(toIndentedString(hints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

