/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.ProfileLinksDescribedBy;
import com.okta.myaccount.myaccountmanagement.model.ProfileLinksSelf;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * ProfileLinks
 */
@JsonPropertyOrder({
  ProfileLinks.JSON_PROPERTY_SELF,
  ProfileLinks.JSON_PROPERTY_DESCRIBED_BY
})
@JsonTypeName("Profile__links")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class ProfileLinks {
  public static final String JSON_PROPERTY_SELF = "self";
  @javax.annotation.Nullable
  private ProfileLinksSelf self;

  public static final String JSON_PROPERTY_DESCRIBED_BY = "describedBy";
  @javax.annotation.Nullable
  private ProfileLinksDescribedBy describedBy;

  public ProfileLinks() {
  }

  public ProfileLinks self(@javax.annotation.Nullable ProfileLinksSelf self) {
    
    this.self = self;
    return this;
  }

  /**
   * Get self
   * @return self
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProfileLinksSelf getSelf() {
    return self;
  }


  @JsonProperty(JSON_PROPERTY_SELF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelf(@javax.annotation.Nullable ProfileLinksSelf self) {
    this.self = self;
  }

  public ProfileLinks describedBy(@javax.annotation.Nullable ProfileLinksDescribedBy describedBy) {
    
    this.describedBy = describedBy;
    return this;
  }

  /**
   * Get describedBy
   * @return describedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIBED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProfileLinksDescribedBy getDescribedBy() {
    return describedBy;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIBED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescribedBy(@javax.annotation.Nullable ProfileLinksDescribedBy describedBy) {
    this.describedBy = describedBy;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileLinks profileLinks = (ProfileLinks) o;
    return Objects.equals(this.self, profileLinks.self) &&
        Objects.equals(this.describedBy, profileLinks.describedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, describedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    describedBy: ").append(toIndentedString(describedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

