/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * JSON Web Token header used for the push notification challenge request JWT
 */
@JsonPropertyOrder({
  PushNotificationChallengeRequestJwtHeader.JSON_PROPERTY_ALG,
  PushNotificationChallengeRequestJwtHeader.JSON_PROPERTY_KID,
  PushNotificationChallengeRequestJwtHeader.JSON_PROPERTY_TYP
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class PushNotificationChallengeRequestJwtHeader {
  public static final String JSON_PROPERTY_ALG = "alg";
  @javax.annotation.Nullable
  private String alg;

  public static final String JSON_PROPERTY_KID = "kid";
  @javax.annotation.Nullable
  private String kid;

  /**
   * Type of token
   */
  public enum TypEnum {
    OKTA_PUSHBIND_JWT(String.valueOf("okta-pushbind+jwt"));

    private String value;

    TypEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypEnum fromValue(String value) {
      for (TypEnum b : TypEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYP = "typ";
  @javax.annotation.Nullable
  private TypEnum typ;

  public PushNotificationChallengeRequestJwtHeader() {
  }

  public PushNotificationChallengeRequestJwtHeader alg(@javax.annotation.Nullable String alg) {
    
    this.alg = alg;
    return this;
  }

  /**
   * Signing algorithm used
   * @return alg
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlg() {
    return alg;
  }


  @JsonProperty(JSON_PROPERTY_ALG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlg(@javax.annotation.Nullable String alg) {
    this.alg = alg;
  }

  public PushNotificationChallengeRequestJwtHeader kid(@javax.annotation.Nullable String kid) {
    
    this.kid = kid;
    return this;
  }

  /**
   * Signing key ID that matches the key ID used by the authorization server
   * @return kid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKid() {
    return kid;
  }


  @JsonProperty(JSON_PROPERTY_KID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKid(@javax.annotation.Nullable String kid) {
    this.kid = kid;
  }

  public PushNotificationChallengeRequestJwtHeader typ(@javax.annotation.Nullable TypEnum typ) {
    
    this.typ = typ;
    return this;
  }

  /**
   * Type of token
   * @return typ
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypEnum getTyp() {
    return typ;
  }


  @JsonProperty(JSON_PROPERTY_TYP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTyp(@javax.annotation.Nullable TypEnum typ) {
    this.typ = typ;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushNotificationChallengeRequestJwtHeader pushNotificationChallengeRequestJwtHeader = (PushNotificationChallengeRequestJwtHeader) o;
    return Objects.equals(this.alg, pushNotificationChallengeRequestJwtHeader.alg) &&
        Objects.equals(this.kid, pushNotificationChallengeRequestJwtHeader.kid) &&
        Objects.equals(this.typ, pushNotificationChallengeRequestJwtHeader.typ);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alg, kid, typ);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushNotificationChallengeRequestJwtHeader {\n");
    sb.append("    alg: ").append(toIndentedString(alg)).append("\n");
    sb.append("    kid: ").append(toIndentedString(kid)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

