/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * Push notification challenge request object for an app authenticator
 */
@JsonPropertyOrder({
  PushNotificationChallenge.JSON_PROPERTY_CHALLENGE,
  PushNotificationChallenge.JSON_PROPERTY_PAYLOAD_VERSION
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class PushNotificationChallenge {
  public static final String JSON_PROPERTY_CHALLENGE = "challenge";
  @javax.annotation.Nullable
  private String challenge;

  /**
   * Gets or Sets payloadVersion
   */
  public enum PayloadVersionEnum {
    IDXV1(String.valueOf("IDXv1"));

    private String value;

    PayloadVersionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PayloadVersionEnum fromValue(String value) {
      for (PayloadVersionEnum b : PayloadVersionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYLOAD_VERSION = "payloadVersion";
  @javax.annotation.Nullable
  private PayloadVersionEnum payloadVersion;

  public PushNotificationChallenge() {
  }

  public PushNotificationChallenge challenge(@javax.annotation.Nullable String challenge) {
    
    this.challenge = challenge;
    return this;
  }

  /**
   * JWT issued by Okta at the time of challenging for a push notification.  This based64-encoded JWT consists of a [JWT header](/openapi/okta-myaccount/myaccount/tag/AppAuthenticator/#tag/AppAuthenticator/schema/PushNotificationChallengeRequestJwtHeader) and a [JWT payload](/openapi/okta-myaccount/myaccount/tag/AppAuthenticator/#tag/AppAuthenticator/schema/PushNotificationChallengeRequestJwt). 
   * @return challenge
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChallenge() {
    return challenge;
  }


  @JsonProperty(JSON_PROPERTY_CHALLENGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChallenge(@javax.annotation.Nullable String challenge) {
    this.challenge = challenge;
  }

  public PushNotificationChallenge payloadVersion(@javax.annotation.Nullable PayloadVersionEnum payloadVersion) {
    
    this.payloadVersion = payloadVersion;
    return this;
  }

  /**
   * Get payloadVersion
   * @return payloadVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYLOAD_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PayloadVersionEnum getPayloadVersion() {
    return payloadVersion;
  }


  @JsonProperty(JSON_PROPERTY_PAYLOAD_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayloadVersion(@javax.annotation.Nullable PayloadVersionEnum payloadVersion) {
    this.payloadVersion = payloadVersion;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PushNotificationChallenge pushNotificationChallenge = (PushNotificationChallenge) o;
    return Objects.equals(this.challenge, pushNotificationChallenge.challenge) &&
        Objects.equals(this.payloadVersion, pushNotificationChallenge.payloadVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(challenge, payloadVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PushNotificationChallenge {\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("    payloadVersion: ").append(toIndentedString(payloadVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

