/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * SendPhoneChallengeRequest
 */
@JsonPropertyOrder({
  SendPhoneChallengeRequest.JSON_PROPERTY_METHOD,
  SendPhoneChallengeRequest.JSON_PROPERTY_RETRY
})
@JsonTypeName("sendPhoneChallenge_request")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class SendPhoneChallengeRequest {
  /**
   * The method with which the challenge should be sent
   */
  public enum MethodEnum {
    SMS(String.valueOf("SMS")),
    
    CALL(String.valueOf("CALL"));

    private String value;

    MethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MethodEnum fromValue(String value) {
      for (MethodEnum b : MethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nonnull
  private MethodEnum method;

  public static final String JSON_PROPERTY_RETRY = "retry";
  @javax.annotation.Nullable
  private Boolean retry = false;

  public SendPhoneChallengeRequest() {
  }

  public SendPhoneChallengeRequest method(@javax.annotation.Nonnull MethodEnum method) {
    
    this.method = method;
    return this;
  }

  /**
   * The method with which the challenge should be sent
   * @return method
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MethodEnum getMethod() {
    return method;
  }


  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMethod(@javax.annotation.Nonnull MethodEnum method) {
    this.method = method;
  }

  public SendPhoneChallengeRequest retry(@javax.annotation.Nullable Boolean retry) {
    
    this.retry = retry;
    return this;
  }

  /**
   * Indicates whether this is a normal challenge or retry
   * @return retry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRetry() {
    return retry;
  }


  @JsonProperty(JSON_PROPERTY_RETRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetry(@javax.annotation.Nullable Boolean retry) {
    this.retry = retry;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendPhoneChallengeRequest sendPhoneChallengeRequest = (SendPhoneChallengeRequest) o;
    return Objects.equals(this.method, sendPhoneChallengeRequest.method) &&
        Objects.equals(this.retry, sendPhoneChallengeRequest.retry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(method, retry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendPhoneChallengeRequest {\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    retry: ").append(toIndentedString(retry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

