/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.AppAuthenticatorMethodCapabilities;
import com.okta.myaccount.myaccountmanagement.model.UpdateAppAuthenticatorEnrollmentRequestMethodsPushKeys;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * UpdateAppAuthenticatorEnrollmentRequestMethodsPush
 */
@JsonPropertyOrder({
  UpdateAppAuthenticatorEnrollmentRequestMethodsPush.JSON_PROPERTY_PUSH_TOKEN,
  UpdateAppAuthenticatorEnrollmentRequestMethodsPush.JSON_PROPERTY_KEYS,
  UpdateAppAuthenticatorEnrollmentRequestMethodsPush.JSON_PROPERTY_CAPABILITIES
})
@JsonTypeName("UpdateAppAuthenticatorEnrollmentRequest_methods_push")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class UpdateAppAuthenticatorEnrollmentRequestMethodsPush {
  public static final String JSON_PROPERTY_PUSH_TOKEN = "pushToken";
  @javax.annotation.Nullable
  private String pushToken;

  public static final String JSON_PROPERTY_KEYS = "keys";
  @javax.annotation.Nullable
  private UpdateAppAuthenticatorEnrollmentRequestMethodsPushKeys keys;

  public static final String JSON_PROPERTY_CAPABILITIES = "capabilities";
  @javax.annotation.Nullable
  private AppAuthenticatorMethodCapabilities capabilities;

  public UpdateAppAuthenticatorEnrollmentRequestMethodsPush() {
  }

  public UpdateAppAuthenticatorEnrollmentRequestMethodsPush pushToken(@javax.annotation.Nullable String pushToken) {
    
    this.pushToken = pushToken;
    return this;
  }

  /**
   * Get pushToken
   * @return pushToken
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUSH_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPushToken() {
    return pushToken;
  }


  @JsonProperty(JSON_PROPERTY_PUSH_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPushToken(@javax.annotation.Nullable String pushToken) {
    this.pushToken = pushToken;
  }

  public UpdateAppAuthenticatorEnrollmentRequestMethodsPush keys(@javax.annotation.Nullable UpdateAppAuthenticatorEnrollmentRequestMethodsPushKeys keys) {
    
    this.keys = keys;
    return this;
  }

  /**
   * Get keys
   * @return keys
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateAppAuthenticatorEnrollmentRequestMethodsPushKeys getKeys() {
    return keys;
  }


  @JsonProperty(JSON_PROPERTY_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeys(@javax.annotation.Nullable UpdateAppAuthenticatorEnrollmentRequestMethodsPushKeys keys) {
    this.keys = keys;
  }

  public UpdateAppAuthenticatorEnrollmentRequestMethodsPush capabilities(@javax.annotation.Nullable AppAuthenticatorMethodCapabilities capabilities) {
    
    this.capabilities = capabilities;
    return this;
  }

  /**
   * Get capabilities
   * @return capabilities
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPABILITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AppAuthenticatorMethodCapabilities getCapabilities() {
    return capabilities;
  }


  @JsonProperty(JSON_PROPERTY_CAPABILITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapabilities(@javax.annotation.Nullable AppAuthenticatorMethodCapabilities capabilities) {
    this.capabilities = capabilities;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAppAuthenticatorEnrollmentRequestMethodsPush updateAppAuthenticatorEnrollmentRequestMethodsPush = (UpdateAppAuthenticatorEnrollmentRequestMethodsPush) o;
    return Objects.equals(this.pushToken, updateAppAuthenticatorEnrollmentRequestMethodsPush.pushToken) &&
        Objects.equals(this.keys, updateAppAuthenticatorEnrollmentRequestMethodsPush.keys) &&
        Objects.equals(this.capabilities, updateAppAuthenticatorEnrollmentRequestMethodsPush.capabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pushToken, keys, capabilities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAppAuthenticatorEnrollmentRequestMethodsPush {\n");
    sb.append("    pushToken: ").append(toIndentedString(pushToken)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

