/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.okta.myaccount.myaccountmanagement.model.UpdateAppAuthenticatorEnrollmentRequestMethods;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * UpdateAppAuthenticatorEnrollmentRequest
 */
@JsonPropertyOrder({
  UpdateAppAuthenticatorEnrollmentRequest.JSON_PROPERTY_METHODS
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class UpdateAppAuthenticatorEnrollmentRequest {
  public static final String JSON_PROPERTY_METHODS = "methods";
  @javax.annotation.Nullable
  private UpdateAppAuthenticatorEnrollmentRequestMethods methods;

  public UpdateAppAuthenticatorEnrollmentRequest() {
  }

  public UpdateAppAuthenticatorEnrollmentRequest methods(@javax.annotation.Nullable UpdateAppAuthenticatorEnrollmentRequestMethods methods) {
    
    this.methods = methods;
    return this;
  }

  /**
   * Get methods
   * @return methods
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METHODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateAppAuthenticatorEnrollmentRequestMethods getMethods() {
    return methods;
  }


  @JsonProperty(JSON_PROPERTY_METHODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethods(@javax.annotation.Nullable UpdateAppAuthenticatorEnrollmentRequestMethods methods) {
    this.methods = methods;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAppAuthenticatorEnrollmentRequest updateAppAuthenticatorEnrollmentRequest = (UpdateAppAuthenticatorEnrollmentRequest) o;
    return Objects.equals(this.methods, updateAppAuthenticatorEnrollmentRequest.methods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(methods);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAppAuthenticatorEnrollmentRequest {\n");
    sb.append("    methods: ").append(toIndentedString(methods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

