/*
 * MyAccount Management
 * APIs for managing a user's own emails, phones, profile, and app authenticators. > **Note:** The MyAccount API doesn't support [delegated authentication](https://help.okta.com/okta_help.htm?id=ext_Security_Authentication).
 *
 * The version of the OpenAPI document: 2025.01.1
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.okta.myaccount.myaccountmanagement.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.okta.myaccount.myaccountmanagement.invoker.JacksonConfig;

/**
 * VerifyPhoneChallengeRequest
 */
@JsonPropertyOrder({
  VerifyPhoneChallengeRequest.JSON_PROPERTY_VERIFICATION_CODE
})
@JsonTypeName("verifyPhoneChallenge_request")
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-08-13T20:31:08.570419254Z[GMT]", comments = "Generator version: unset")
public class VerifyPhoneChallengeRequest {
  public static final String JSON_PROPERTY_VERIFICATION_CODE = "verificationCode";
  @javax.annotation.Nonnull
  private String verificationCode;

  public VerifyPhoneChallengeRequest() {
  }

  public VerifyPhoneChallengeRequest verificationCode(@javax.annotation.Nonnull String verificationCode) {
    
    this.verificationCode = verificationCode;
    return this;
  }

  /**
   * A six-digit verification code that the user receives through SMS or CALL
   * @return verificationCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERIFICATION_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVerificationCode() {
    return verificationCode;
  }


  @JsonProperty(JSON_PROPERTY_VERIFICATION_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerificationCode(@javax.annotation.Nonnull String verificationCode) {
    this.verificationCode = verificationCode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyPhoneChallengeRequest verifyPhoneChallengeRequest = (VerifyPhoneChallengeRequest) o;
    return Objects.equals(this.verificationCode, verifyPhoneChallengeRequest.verificationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verificationCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyPhoneChallengeRequest {\n");
    sb.append("    verificationCode: ").append("*").append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

