/*
 * Harry Potter API
 * A REST Harry Potter API with images and information about books, characters and spells. Translated to many languages.  This documentation was built by Víctor Laurencena and it's available on [GitHub](https://github.com/vlaurencena/harry-potter-openapi-swagger-ui). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.radiantlogic.openapi.generated.harrypotterapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.radiantlogic.openapi.generated.harrypotterapi.invoker.JacksonConfig;

/**
 * Character
 */
@JsonPropertyOrder({
  Character.JSON_PROPERTY_FULLNAME,
  Character.JSON_PROPERTY_NICKNAME,
  Character.JSON_PROPERTY_HOGWARTS_HOUSE,
  Character.JSON_PROPERTY_INTERPRETED_BY,
  Character.JSON_PROPERTY_CHILDREN,
  Character.JSON_PROPERTY_IMAGE,
  Character.JSON_PROPERTY_BIRTH_DATE,
  Character.JSON_PROPERTY_INDEX
})
@javax.annotation.Generated(value = "com.radiantlogic.openapi.codegen.javaclient.generate.codegen.RadiantJavaClientCodegen", date = "2025-07-20T12:50:53.280565630Z[GMT]", comments = "Generator version: unset")
public class Character {
  public static final String JSON_PROPERTY_FULLNAME = "fullname";
  @javax.annotation.Nullable
  private String fullname;

  public static final String JSON_PROPERTY_NICKNAME = "nickname";
  @javax.annotation.Nullable
  private String nickname;

  public static final String JSON_PROPERTY_HOGWARTS_HOUSE = "hogwartsHouse";
  @javax.annotation.Nullable
  private String hogwartsHouse;

  public static final String JSON_PROPERTY_INTERPRETED_BY = "interpretedBy";
  @javax.annotation.Nullable
  private String interpretedBy;

  public static final String JSON_PROPERTY_CHILDREN = "children";
  @javax.annotation.Nullable
  private List<String> children = new ArrayList<>();

  public static final String JSON_PROPERTY_IMAGE = "image";
  @javax.annotation.Nullable
  private String image;

  public static final String JSON_PROPERTY_BIRTH_DATE = "birthDate";
  @javax.annotation.Nullable
  private String birthDate;

  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nullable
  private Integer index;

  public Character() {
  }

  public Character fullname(@javax.annotation.Nullable String fullname) {
    
    this.fullname = fullname;
    return this;
  }

  /**
   * Get fullname
   * @return fullname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULLNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullname() {
    return fullname;
  }


  @JsonProperty(JSON_PROPERTY_FULLNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullname(@javax.annotation.Nullable String fullname) {
    this.fullname = fullname;
  }

  public Character nickname(@javax.annotation.Nullable String nickname) {
    
    this.nickname = nickname;
    return this;
  }

  /**
   * Get nickname
   * @return nickname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NICKNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNickname() {
    return nickname;
  }


  @JsonProperty(JSON_PROPERTY_NICKNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNickname(@javax.annotation.Nullable String nickname) {
    this.nickname = nickname;
  }

  public Character hogwartsHouse(@javax.annotation.Nullable String hogwartsHouse) {
    
    this.hogwartsHouse = hogwartsHouse;
    return this;
  }

  /**
   * Get hogwartsHouse
   * @return hogwartsHouse
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOGWARTS_HOUSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHogwartsHouse() {
    return hogwartsHouse;
  }


  @JsonProperty(JSON_PROPERTY_HOGWARTS_HOUSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHogwartsHouse(@javax.annotation.Nullable String hogwartsHouse) {
    this.hogwartsHouse = hogwartsHouse;
  }

  public Character interpretedBy(@javax.annotation.Nullable String interpretedBy) {
    
    this.interpretedBy = interpretedBy;
    return this;
  }

  /**
   * Get interpretedBy
   * @return interpretedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERPRETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInterpretedBy() {
    return interpretedBy;
  }


  @JsonProperty(JSON_PROPERTY_INTERPRETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterpretedBy(@javax.annotation.Nullable String interpretedBy) {
    this.interpretedBy = interpretedBy;
  }

  public Character children(@javax.annotation.Nullable List<String> children) {
    
    this.children = children;
    return this;
  }

  public Character addChildrenItem(String childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

  /**
   * Get children
   * @return children
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getChildren() {
    return children;
  }


  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChildren(@javax.annotation.Nullable List<String> children) {
    this.children = children;
  }

  public Character image(@javax.annotation.Nullable String image) {
    
    this.image = image;
    return this;
  }

  /**
   * Get image
   * @return image
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(@javax.annotation.Nullable String image) {
    this.image = image;
  }

  public Character birthDate(@javax.annotation.Nullable String birthDate) {
    
    this.birthDate = birthDate;
    return this;
  }

  /**
   * Get birthDate
   * @return birthDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIRTH_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBirthDate() {
    return birthDate;
  }


  @JsonProperty(JSON_PROPERTY_BIRTH_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBirthDate(@javax.annotation.Nullable String birthDate) {
    this.birthDate = birthDate;
  }

  public Character index(@javax.annotation.Nullable Integer index) {
    
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIndex() {
    return index;
  }


  @JsonProperty(JSON_PROPERTY_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndex(@javax.annotation.Nullable Integer index) {
    this.index = index;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Character character = (Character) o;
    return Objects.equals(this.fullname, character.fullname) &&
        Objects.equals(this.nickname, character.nickname) &&
        Objects.equals(this.hogwartsHouse, character.hogwartsHouse) &&
        Objects.equals(this.interpretedBy, character.interpretedBy) &&
        Objects.equals(this.children, character.children) &&
        Objects.equals(this.image, character.image) &&
        Objects.equals(this.birthDate, character.birthDate) &&
        Objects.equals(this.index, character.index);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullname, nickname, hogwartsHouse, interpretedBy, children, image, birthDate, index);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Character {\n");
    sb.append("    fullname: ").append(toIndentedString(fullname)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    hogwartsHouse: ").append(toIndentedString(hogwartsHouse)).append("\n");
    sb.append("    interpretedBy: ").append(toIndentedString(interpretedBy)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

